name: CI # Continuous Integration

on:	
  push:
    branches:
      - main

jobs:

  build: 
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }} # possibly not needed, but I cannot be bothered to test this
        password: ${{ secrets.TOKEN }}

    - name: Get Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: | # tag with commit hash and with 'latest'
          type=sha 
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}